In [174]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/Raw/GoogleAds_DataAnalytics_Sales_Uncleaned.csv")
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,$231.88,14.0,7.0,0.058,$1892,2024-11-16,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,$216.84,10.0,8.0,0.046,$1679,20-11-2024,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,$203.66,26.0,9.0,NaN,$1624,2024/11/16,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,$237.66,17.0,6.0,NaN,$1225,2024-11-26,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,$195.9,30.0,8.0,NaN,$1091,2024-11-22,hyderabad,desktop,online data analytic

In [175]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ad_ID            2600 non-null   str
 1   Campaign_Name    2600 non-null   str
 2   Clicks           2488 non-null   float64
 3   Impressions      2546 non-null   float64
 4   Cost             2503 non-null   str
 5   Leads            2552 non-null   float64
 6   Conversions      2526 non-null   float64
 7   Conversion Rate  1974 non-null   float64
 8   Sale_Amount      2461 non-null   str
 9   Ad_Date          2600 non-null   str
 10  Location         2600 non-null   str
 11  Device           2600 non-null   str
 12  Keyword          2600 non-null   str
dtypes: float64(5), str(8)
memory usage: 264.2 KB

In [176]:
df.describe()

            Clicks  Impressions        Leads  Conversions  Conversion Rate
count  2488.000000  2546.000000  2552.000000  2526.000000      1974.000000
mean    138.956994  4523.280833    20.003918     6.519002         0.048979
std      34.619376   869.927913     6.032317     2.272573         0.019987
min      80.000000  3000.000000    10.000000     3.000000         0.015000
25%     110.000000  3764.000000    15.000000     5.000000         0.035000
50%     139.000000  4518.500000    20.000000     7.000000         0.046000
75%     169.000000  5279.500000    25.000000     9.000000         0.058000
max     199.000000  5999.000000    30.000000    10.000000         0.123000

In [177]:
df.isnull().sum()

Ad_ID                0
Campaign_Name        0
Clicks             112
Impressions         54
Cost                97
Leads               48
Conversions         74
Conversion Rate    626
Sale_Amount        139
Ad_Date              0
Location             0
Device               0
Keyword              0
dtype: int64

In [178]:
df["Conversion Rate"].value_counts()

Conversion Rate
0.050    51
0.045    51
0.036    51
0.037    50
0.038    49
         ..
0.108     2
0.114     1
0.123     1
0.113     1
0.109     1
Name: count, Length: 105, dtype: int64

In [179]:
df["Conversion Rate"].describe()

count    1974.000000
mean        0.048979
std         0.019987
min         0.015000
25%         0.035000
50%         0.046000
75%         0.058000
max         0.123000
Name: Conversion Rate, dtype: float64

In [180]:
df["Conversion Rate"] = df["Conversion Rate"].fillna(df["Conversion Rate"].mean())

In [181]:
df["Conversion Rate"].isnull().sum()

np.int64(0)

In [182]:
df["Sale_Amount"].value_counts()

Sale_Amount
$1719    9
$1248    8
$1234    8
$1571    8
$1555    8
        ..
$1787    1
$1302    1
$1717    1
$1889    1
$1702    1
Name: count, Length: 921, dtype: int64

In [183]:
#df["Sale_Amount"] = df["Sale_Amount"].str.replace('$', '', regex=False)
#df["Sale_Amount"] = df["Sale_Amount"].str.replace(',', '', regex=False)

df["Sale_Amount"] = (
    df["Sale_Amount"]
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [184]:
df["Sale_Amount"]

0       1892.0
1       1679.0
2       1624.0
3       1225.0
4       1091.0
         ...
2595    1418.0
2596    1950.0
2597    1085.0
2598    1558.0
2599    1174.0
Name: Sale_Amount, Length: 2600, dtype: float64

In [185]:
df["Sale_Amount"].isnull().sum()

np.int64(139)

In [186]:
#df["Sale_Amount"] = df["Sale_Amount"].astype(int)
df["Sale_Amount"].describe()

count    2461.000000
mean     1498.648111
std       287.106579
min      1000.000000
25%      1248.000000
50%      1505.000000
75%      1742.000000
max      2000.000000
Name: Sale_Amount, dtype: float64

In [187]:
df["Sale_Amount"].head()

0    1892.0
1    1679.0
2    1624.0
3    1225.0
4    1091.0
Name: Sale_Amount, dtype: float64

In [188]:
df["Sale_Amount"] = (
    df["Sale_Amount"]
    .fillna(df["Sale_Amount"].mean())
)

In [189]:
df["Sale_Amount"].isnull().sum()

np.int64(0)

In [190]:
df.isnull().sum()

Ad_ID                0
Campaign_Name        0
Clicks             112
Impressions         54
Cost                97
Leads               48
Conversions         74
Conversion Rate      0
Sale_Amount          0
Ad_Date              0
Location             0
Device               0
Keyword              0
dtype: int64

In [191]:
df["Conversions"].head().value_counts(ascending=False)

Conversions
8.0    2
7.0    1
9.0    1
6.0    1
Name: count, dtype: int64

In [192]:
df["Conversions"].value_counts()

Conversions
7.0     345
9.0     330
5.0     324
4.0     313
10.0    306
8.0     304
6.0     302
3.0     302
Name: count, dtype: int64

In [193]:
df["Conversions"].unique()

array([ 7.,  8.,  9.,  6.,  5.,  3.,  4., 10., nan])

In [194]:
df["Conversions"].describe()

count    2526.000000
mean        6.519002
std         2.272573
min         3.000000
25%         5.000000
50%         7.000000
75%         9.000000
max        10.000000
Name: Conversions, dtype: float64

In [197]:
df["Conversions"] = (
    df["Conversions"]
    .fillna(df["Conversions"].mean())
)

In [199]:
df["Conversions"].isnull().sum()

np.int64(0)