In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns 

df = pd.read_csv("../Data/GoogleAds_DataAnalytics_Sales_Cleaned.csv")
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,231.88,14.0,7.0,0.058000,1892.0,2024-11-16,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,216.84,10.0,8.0,0.046000,1679.0,20-11-2024,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,203.66,26.0,9.0,0.048979,1624.0,2024/11/16,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,237.66,17.0,6.0,0.048979,1225.0,2024-11-26,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,195.90,30.0,8.0,0.048979,1091.0,2024-11-22,hyderabad,desktop,online data analytic

In [11]:
df['Ad_Date'] = pd.to_datetime(df['Ad_Date'], format='%d/%m/%Y', errors='coerce')
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,231.88,14.0,7.0,0.058000,1892.0,NaT,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,216.84,10.0,8.0,0.046000,1679.0,NaT,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,203.66,26.0,9.0,0.048979,1624.0,NaT,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,237.66,17.0,6.0,0.048979,1225.0,NaT,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,195.90,30.0,8.0,0.048979,1091.0,NaT,hyderabad,desktop,online data analytic

In [14]:
df["Ad_Date"]

0      NaT
1      NaT
2      NaT
3      NaT
4      NaT
        ..
2595   NaT
2596   NaT
2597   NaT
2598   NaT
2599   NaT
Name: Ad_Date, Length: 2600, dtype: datetime64[s]

In [18]:
df['Ad_Date'] = pd.to_datetime(df['Ad_Date'], dayfirst=True, errors='coerce')
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,231.88,14.0,7.0,0.058000,1892.0,NaT,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,216.84,10.0,8.0,0.046000,1679.0,NaT,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,203.66,26.0,9.0,0.048979,1624.0,NaT,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,237.66,17.0,6.0,0.048979,1225.0,NaT,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,195.90,30.0,8.0,0.048979,1091.0,NaT,hyderabad,desktop,online data analytic