In [19]:
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns 

df = pd.read_csv("../Data/GoogleAds_DataAnalytics_Sales_Cleaned.csv")
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,231.88,14.0,7.0,0.058000,1892.0,2024-11-16,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,216.84,10.0,8.0,0.046000,1679.0,20-11-2024,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,203.66,26.0,9.0,0.048979,1624.0,2024/11/16,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,237.66,17.0,6.0,0.048979,1225.0,2024-11-26,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,195.90,30.0,8.0,0.048979,1091.0,2024-11-22,hyderabad,desktop,online data analytic

In [20]:
df.shape

(2600, 13)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ad_ID            2600 non-null   str
 1   Campaign_Name    2600 non-null   str
 2   Clicks           2600 non-null   float64
 3   Impressions      2600 non-null   float64
 4   Cost             2600 non-null   float64
 5   Leads            2600 non-null   float64
 6   Conversions      2600 non-null   float64
 7   Conversion Rate  2600 non-null   float64
 8   Sale_Amount      2600 non-null   float64
 9   Ad_Date          2600 non-null   str
 10  Location         2600 non-null   str
 11  Device           2600 non-null   str
 12  Keyword          2600 non-null   str
dtypes: float64(7), str(6)
memory usage: 264.2 KB

In [23]:
df["Ad_Date"] = (
    df["Ad_Date"]
    .astype("datetime64[ns]")
)

df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,231.88,14.0,7.0,0.058000,1892.0,2024-11-16,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,216.84,10.0,8.0,0.046000,1679.0,2024-11-20,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,203.66,26.0,9.0,0.048979,1624.0,2024-11-16,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,237.66,17.0,6.0,0.048979,1225.0,2024-11-26,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,195.90,30.0,8.0,0.048979,1091.0,2024-11-22,hyderabad,desktop,online data analytic